name: Get_tool_version
on:
  workflow_dispatch:

jobs:
  version_job:
    name: Create version number
    runs-on: ubuntu-latest
    steps:
    - id: version_step
      run: echo "::set-output name=version_number::1.2.3"

  output:
    name: Output
    runs-on: ubuntu-latest
    needs: version_job
    steps:
    - run: echo "${{ needs.version_job.steps.version_step.outputs.version_number }}"