name: Test Python version
on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: ['pypy-3.8-v7.3.8']
    steps:
    - uses: actions/checkout@v2
    - name: Set up PyPy
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test
      run: echo $PATH