name: Test Python version
on: 
  workflow_dispatch:

jobs:
  test-python:
    name: Test Python
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout source
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip3 install virtualenv
        python3 -m venv C:\temp\venv
        dir C:\temp\venv\Scripts
        C:\temp\venv\Scripts\activate.bat
        pip3 install matplotlib scons
