name: Test setup-python
on:
  push:
  workflow_dispatch:

jobs:
  test-python:
    name: Test Python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      name: Checkout source
    # - name: where python
    #   run: |
    #     which python
    #     which python3
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: where python
      run: |
        where python
        where python3
