name: Test setup-python
on:
  push:
  workflow_dispatch:

jobs:
  test-python:
    name: Test Python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      name: Checkout source
    # - name: where python
    #   run: |
    #     which python
    #     which python3
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: where python
      run: |
        pkg-config --debug 2>&1 | grep directory
        

    - name: where python
      run: |
        pkg-config --variable pc_path pkg-config

