name: Test Python version
on: 
  workflow_dispatch:
  push:

jobs:
  test-python:
    name: Test Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.9']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version }}
    - name: test
      run: |
        ls -a /opt/hostedtoolcache/Python/3.9.9/x64
