name: Test Python version
on: 
  workflow_dispatch:
    inputs:
      architecture:
        description: 'The target architecture (x86, x64) of the Python'
        required: false
        default: 'x64'

jobs:
  test-python:
    name: Test Python ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.6.12', '3.7.8', '3.8.5', '3.6.7', '3.7.3']
    steps:
    - name: Setup Python ${{ matrix.python }}
      uses: nikita-bykov/setup-python@test-branch
      with:
        python-version: '3.9'
        architecture: ${{ github.event.inputs.architecture }}
        cache: 'pip'

    - name: Validate version
      run: |
        python --version

    - run: pip install -r requirements.txt
    - run: pip test
    # - name: Run simple code
    #   run: |
    #     Write Host $env:PATH
    #   shell: powershell
    # - name: Run simple code
    #   run: |
    #     python -m pip install --upgrade pip wheel
    #     pip install flake8 pytest
    #     pip install shap
