name: Python
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.12'

      - name: pip3 version
        run: pip --version

      - name: show python path
        run: python -c "import sys; print('\n'.join(sys.path))"

      - name: install random pip package
        run: sudo pip install pipdate

      - name: pip show install package
        run: sudo pip show pipdate

      - name: install python package from apt
        run: pip install openbabel

      - name: show openbabel python files
        run: dpkg -L python3-openbabel
