name: Test Python version
on: 
  workflow_dispatch:
  push:

jobs:
  test-python:
    name: Test Python
    runs-on: macos-latest
    strategy:
      matrix:
        version: ['pypy-3.7-v7.3.4']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version }}
