name: Python
on:
  workflow_dispatch:
jobs:
  test-python:
    name: Test Python ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python: ['3.10', '3.9.7', '3.9.9', '3.9']
    steps:
    - name: Setup Python ${{ matrix.python }}
      uses: nikita-bykov/setup-python@test-branch
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ github.event.inputs.architecture }}

    - name: Validate version
      run: |
        python --version
      shell: pwsh

    - name: Run simple code
      run: |
        python -c "from pathlib import Path; (Path.cwd() / ('a'*131) / ('a'*131)).mkdir(parents=True)"

