name: Test Python version
on: 
  workflow_dispatch:

jobs:
  test-python:
    name: Test Python
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout source
    - uses: actions/setup-python@v2
      with:
          python-version: "3.9"
      name: Install Python
    # - run: pip install virtualenv
    # - run: pip3 list
    # - run: pip list
    - name: Install dependencies
      run: |
        # pip3 install virtualenv
        python3 -m venv C:\temp\venv
        ls "C:\temp\venv\Scripts"
        C:\temp\venv\Scripts\activate.bat
