name: Test Python version
on: 
  workflow_dispatch:
  push:

jobs:
  test-python:
    name: Test Python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: ['3.8']
        os: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version }}
    - name: test
      run: |
        export PKG_CONFIG_PATH=$pythonLocation/lib/pkgconfig
        echo $PKG_CONFIG_PATH
        pkg-config python-3.8-embed --libs --cflags
        python3-config --libs
