name: Test Python version
on: 
  workflow_dispatch:
  push:

jobs:
  test-python:
    name: Test Python
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        ls /Users/runner/hostedtoolcache
        python3 -m venv /Users/runner/hostedtoolcache/venv
        ls /Users/runner/hostedtoolcache/venv
#        dir C:\temp\venv\Scripts
#        C:\temp\venv\Scripts\activate.bat
