name: Test Python version
on: 
  workflow_dispatch:
    inputs:
      architecture:
        description: 'The target architecture (x86, x64) of the Python'
        required: false
        default: 'x64'

jobs:
  test-python:
    name: Test Python ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ['3.9']
    steps:
    - uses: actions/checkout@v2
    - name: Validate version
      run: |
        python --version

    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ github.event.inputs.architecture }}
        cache: 'pip'


