name: Test Python version
on: 
  workflow_dispatch:
    inputs:
      architecture:
        description: 'The target architecture (x86, x64) of the Python'
        required: false
        default: 'x64'

jobs:
  test-python:
    name: Test Python ${{ matrix.versions }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]
        versions: ["pypy3"]
    steps:
    - name: Setup Python ${{ matrix.versions }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.versions }}
        architecture: ${{ github.event.inputs.architecture }}

    - name: Validate version
      run: |
        python --version
      shell: pwsh

    # - name: Run simple code
    #   run: |
    #     python -m pip install --user -e .[dev]