name: Test Python version
on: 
  workflow_dispatch:
    inputs:
      architecture:
        description: 'The target architecture (x86, x64) of the Python'
        required: false
        default: 'x64'

jobs:
  test-python:
    name: Test Python ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ['3.x', '3.6', '3.8', '3.9']
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ github.event.inputs.architecture }}
        cache: 'pip'

    - name: Validate version
      run: |
        tempVar=$(python -c "import distutils.sysconfig as sysconfig; import sys;  print('{0}/python{1}'.format(sysconfig.get_config_var('LIBDIR'), '.'.join(map(str, sys.version_info[:2]))))")
        echo $tempVar

