name: Test Python version
on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up PyPy
      uses: actions/setup-python@v2
      with:
        python-version: "pypy-3.7"
    - name: Test
      run: python test_sqlite_version.py
