name: Test Python version
on: 
  push:
  workflow_dispatch:
    inputs:
      architecture:
        description: 'The target architecture (x86, x64) of the Python'
        required: false
        default: 'x64'

jobs:
  test-python:
    name: Test Python ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ['3.9']
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ github.event.inputs.architecture }}
        cache: 'pip'

    - name: Packages by default
      run: |
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python get-pip.py pip==21.0.1
        pip freeze

    - name: Packages by default with sudo
      run: |
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        sudo python get-pip.py pip==21.0.1
        sudo pip freeze

    - name: Validate version
      run: |
        python --version
        echo $PATH

    - name: Validate sudo version
      run: |
        sudo python --version
        sudo echo $PATH

