name: Test Python version
on: 
  workflow_dispatch:
    inputs:
      architecture:
        description: 'The target architecture (x86, x64) of the Python'
        required: false
        default: 'x64'

jobs:
  test-python:
    name: Test Python ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.6', '3.7', '3.8', '3.9']
    steps:
    - name: Setup Python ${{ matrix.python }}
      uses: nikita-bykov/setup-python@test-branch
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ github.event.inputs.architecture }}

    - name: Validate version
      run: |
        python --version
        setuptools --version

    # - name: Run simple code
    #   run: |
    #     Write Host $env:PATH
    #   shell: powershell
    - name: Run simple code
      run: |
        python -m pip install --upgrade pip wheel
        pip install flake8 pytest
        pip install shap
        setuptools --version
