name: Test Python version
on: 
  workflow_dispatch:
  push:

jobs:
  test-python:
    name: Test Python
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        version: ['3.8']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version }}
    - name: test
      run: |
        pkg-config python-3.8 --libs
