name: Test Python version
on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        version: ['pypy-3.7-v7.3.8']
    steps:
    - uses: actions/checkout@v2
    - name: Set up PyPy
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version }}
    - name: Test
      run: python test_sqlite_version.py
