name: Test Python version
on: 
  workflow_dispatch:

jobs:
  test-python:
    name: Test Python ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python: ['pypy-3.x']
    steps:
    - uses: actions/checkout@v2

    - name: homebrew
      run: |
        # Download and run the uninstall script.
        curl -sLO https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh
        chmod +x ./uninstall.sh
        sudo ./uninstall.sh --force
        # Clean up Homebrew directories.
        sudo rm -rf /usr/local/Homebrew
        sudo rm -rf /usr/local/Caskroom
        sudo rm -rf /usr/local/bin/brew

    - name: Setup Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        cache: 'pip'
