name: Create Pull Request
on: push

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ 'pypy3' ]
    name: ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: nikita-bykov/setup-python@improve-usepypy-on-windows
        continue-on-error: true
        with:
          python-version: ${{ matrix.python-version }}

      - name: Remove bin folder
        run: |
          python --version
          ls "C:/hostedtoolcache/windows/PyPy/3.6.12/x86/Scripts"
          rm -r "C:/hostedtoolcache/windows/PyPy/3.6.12/x86/bin"

      - name: Check bin folder
        run: Get-ChildItem -Path "C:/hostedtoolcache/windows/PyPy/3.6.12/x86"

      - name: "Test"
        run: |
          python --version
          echo $PATH
          pip install arrow
          python -c "import arrow;print(arrow.get('2013-05-11T21:23:58.970460+07:00'))"
        shell: bash 