name: tar-test
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Unpack"
        run: tar -xzf qi-macos.tar.gz
        shell: bash 

      - name: "Pack"
        run: | 
          tar -cvf qi1-macos.tar.gz qi
          gzip qi.tar  > qi.tgz
          du -ah qi1-macos.tar.gz
        shell: bash 